### PR TITLE
Proposal and implementation of fixed-width ranges

### PR DESCRIPTION
**Pull request by PeteHaitch**
Hi @hpages and @lawremi,

I'd like to propose the concept of fixed-width / constant-width ranges and an implementation for inclusion in **IRanges** and **GenomicRanges**.

My motivation comes from analysing bisulfite-sequencing data where we may have hundreds of millions of non-adjacent loci all with width of 1.
The current options of storing these as *IRanges* (within a *GRanges*) or *IPos* (within a *GPos*) aren't optimal:
- There is a lot of redundancy when these loci are stored as an *IRanges* object (within a *GRanges* object) because all loci have `start == end`.
- The *IPos* / *GPos* classes aren't efficient for these loci because they are (almost) never adjacent.

My proposal is store only the `start` of these loci (n values) along with their common `fixed_width` (1 value).
For 100,000,000 loci, this halves the object size from ~800 Mb to ~400 Mb.

For a while now, I've had a hacky and incomplete implementation of this idea in the **bsseq** package, and I've long been wanting to tidy it up and finalise it.
Here, I've implemented this idea in the *IFWRanges* class, which serves as a drop-in replacement for *IRanges* in much the same way as *IPos*.

First and foremost, would you be interested in including this in **IRanges**  and **GenomicRanges**? 
These package seem to me the natural homes for these classes and methods, but I guess the alternative is for them to live in their own package.

Secondly, I've got some questions about the implementation where I would appreciate your advice.

1. Have I got the class hierarchy correct? I (manually) updated the ASCII diagram of the class hierarchy to illustrate it: https://github.com/PeteHaitch/IRanges/blob/11d2b45dd7b4d70a5257cef39d18b72a5e8fc0fb/R/Ranges-and-RangesList-classes.R#L23-L46
2. I think the `fixed_width()` generic (and methods) need be exported because *GFWRanges*, which I have written as a patch to **GenomicRanges** (I'll await feedback on this PR before submitting this second PR), will require an implementation. If so:
    a. Should the `fixed_width()` generic be here or in **BiocGenerics** (like `pos()`)?
    b. Is there a way to a have a "developer-facing but not user-facing" cross-package generic? I don't see much need for `fixed_width()` to be user-facing.
3. Should I define an `update_ranges,IFWRanges-method`? It would be extremely limited by design because arbitary intra-range operations on an *IFWRanges* object are not supported, but it would give me a cheap implementation of `resize()` as well as a 'better' implementation of `shift,IFWRanges-method` and (ultimately) `shift,GFWRanges-method`.
4. Following the *IPos* hierarchy, I've not implemented `start()<-` or `end()<-` for the *IFWRanges* hierarchy (since arbitrary changes of either are not supported on fixed-width ranges), but I have implemented a limited `width<-()` since this is easily done. Is this asymmetry okay?
5. `show,IFWRanges-method` defers to `show,IPosRanges-method` which coerces the input to an *IRanges* object. This coercion will double the memory footprint of the object, which it'd be nice to avoid. There's a note in `show_IPosRanges()` saying:
https://github.com/Bioconductor/IRanges/blob/b93d3d18e2a4f821c30094ab02b94fe2181d17f0/R/IPosRanges-class.R#L138-L140
  a. Which *IPosRanges* objects are not subsettable?
  b. Subsetting *IFWRanges* is cheap, so could this coercion perhaps be skipped if `show_IPosRanges()` is given an *IFWRanges* object?
6. The depth of documentation and unit tests is roughly on part with that for the *IPos* hierarchy :)
7. I'm not sure the name "fixed-width" is accurate. For example, it's possible to change the width (e.g., `width(x) <- 2L`) so it's not fixed in that sense. Perhaps constant width is better. I particularly started to think this upon noting the comment below.

While implementing the *IFWRanges* hierarchy, I noticed the `is_constant_width` member of the `struct iranges_holder`.
https://github.com/Bioconductor/IRanges/blob/b93d3d18e2a4f821c30094ab02b94fe2181d17f0/inst/include/IRanges_defines.h#L46-L55
However, it doesn't seem to be used much (at all?) in the code base, so:
    8a. What's this about?
    8b. Could the proposed *IFWRanges* class make use of this?

There's a few other things on my TODO list should this be considered worthwhile:

- [ ] Deal with remaining inline TODOs
- [ ] Update `DESCRIPTION`
    - [ ] Bump version number
    - [ ] Add self to authors
- [ ] Update `NEWS`
- [ ] Document `fixed_width()` (once I know where it's living).
- [ ] Tidy up `.normarg_fixed_width()`. There should be a specific error message depending on the function it is called from (right now, this is half-baked).
- [ ] Add unit tests

I look forward to hearing your thoughts.
Thanks,
Pete

### CODE REVIEW

**Comment by PeteHaitch** [comment]
Any thoughts - good or bad - on this?

**Comment by hpages** [comment]
Hi Pete,

I saw this and started to give it some thoughts over the weekend.

The current implementation of the IPos / GPos classes is just an implementation. We need to distinguish between implementation and semantic. The semantic of the IPos / GPos containers is to store single base loci (i.e. 1-width ranges). The fact that the current implementation is optimized towards long runs of adjacent loci is only incidental, it's only because this was the use case that motivated the introduction of these objects. What we should do is make IPos and GPos virtual and have concrete subclasses for the "runs of adjacent loci" use case (e.g. AdjIPos and AdjGPos, names are subject to change) as well as more general concrete subclasses for the "random loci" use case (SimpleIPos and SimpleGPos). The current IPos and GPos would become the AdjIPos and AdjGPos classes. SimpleIPos and SimpleGPos would be new subclasses and support your use case.

Note that this approach is similar to the SimpleList/CompressedList stuff that we already have in many places (e.g. SimpleCharacterList/CompressedCharacterList, SimpleRleList/CompressedRleList, etc...). Most of the time which implementation is used behind the scene is transparent to the user i.e. the user sees a CharacterList or RleList object and operates on it without knowing whether it's a SimpleCharacterList or CompressedCharacterList instance. It would be the same with an IPos or GPos object.

So I'd like to start by making the required changes to IRanges and GenomicRanges to accomodate for these new IPos and GPos hierarchy. I'll work on this this week. Note that the question of how we want to handle fixed-width ranges of arbitrary width is a more complicated one but maybe it can wait. My understanding is that you need the "random loci" IPos/GPos containers for your use case. Let's focus on that. Just throwing an idea for the "fixed-width ranges of arbitrary width" use case that maybe you've already considered and discarded: how about changing the definition of the IRanges class to have the `start` and `width` slots be `Integer_OR_Rle` objects? As an alternative to the IFWRanges approach. Of course this would have many consequences on the entire IRanges/GRanges framework so would need to be done carefully but maybe that is worth exploring.

H.

**Comment by lawremi** [comment]
If you go the `Integer_OR_Rle` route, be sure to consider/merge `VariantAnnotation::setAtomicRleUnion()`.

**Comment by PeteHaitch** [comment]
Thanks for such a considered reply, Herve.

The idea that the current *IPos* is also a fixed-width range did cross my mind, but since it required messing with the class hierarchy some more I opted against it for this initial proposal.

I do think it would be worthwhile 'virtualising' some of these semantics and I like your proposed implementation.
You're correct that my use case is that I'd like the "random loci" *IPos*/*Gpos* containers.
Whether general fixed-width ranges are worthwhile I'm less certain, but under my implementation these were a zero-cost abstraction so I did it whereas under yours (which to be clear I think is probably a better abstraction) it's perhaps less obvious how to do this.
I did think of storing the width as an *Rle* (in line with the `Integer_OR_Rle` idea) but didn't spend a great deal of thought or experiment with an implementation.

I look forward to seeing what you come up with!

**Comment by hpages** [comment]
Hi Pete,

So commit 3e4ac3f6060eb791901604dec4bb1bd692654913 implements the little IPos class hierarchy (IPos is virtual with concrete subclasses UnstitchedIPos and StitchedIPos). Still need to work on the GPos side of things i.e. also make GPos virtual with concrete subclasses UnstitchedGPos and StitchedGPos. Also will need to think about the implications of these changes on the IPosList/GPosList side of things.

Some notes/questions:
- Note that IPos (and consequently GPos) objects still can't hold names at the moment. I guess they could, and this would be easy to support. 
- Still no `pos()` **setter** for IPos/GPos objects. Is this something we should have? At least in the "unstitched" case?
- The `show()` method for IPos objects displays the flavor of the object (i.e. UnstitchedIPos or StitchedIPos). Note that this differs from what we're doing with the SimpleList/CompressedList flavors of List objects where `show()` doesn't show the exact flavor of the object (e.g. `show(x)` will print "CharacterList object" whether `x` is SimpleCharacterList or CompressedCharacterList). The reason I'm not doing this for IPos objects is because, unlike for List objects, the flavor of an IPos object is actually likely to matter to the end user. Hopefully that makes sense. We can always change this in the future if we want (the change would be very easy and not disruptive).
- IPos objects inherit a bunch of methods from IntegerRanges objects. Some of them, like the comparison methods (`==`, `<=`, etc...), or `reduce()`, work as expected but could be overwritten by methods that are optimized for IPos objects. I'm putting this on the TODO list.

Let me know what you think.

H.

**Comment by PeteHaitch** [comment]
Hi Herve,

> Note that IPos (and consequently GPos) objects still can't hold names at the moment. I guess they could, and this would be easy to support.

Supporting names would be nice, e.g., CpGs on a methylation array have IDs (https://www.illumina.com/Documents/products/technotes/technote_cpg_loci_identification.pdf)

> Still no `pos()` setter for IPos/GPos objects. Is this something we should have? At least in the "unstitched" case?

I think I don't the mental model correct so take this with a grain of salt: I think of `pos()`/`pos()<-`() as special cases of `ranges()`/`ranges()<-` or even `start()`/`start()<-`, so whether they need to exist or not depends on whether it's okay to instead just overload `ranges()`/`ranges()<-`?

> The `show()` method for IPos objects displays the flavor of the object (i.e. UnstitchedIPos or StitchedIPos). Note that this differs from what we're doing with the SimpleList/CompressedList flavors of List objects where show() doesn't show the exact flavor of the object (e.g. show(x) will print "CharacterList object" whether x is SimpleCharacterList or CompressedCharacterList). The reason I'm not doing this for IPos objects is because, unlike for List objects, the flavor of an IPos object is actually likely to matter to the end user. Hopefully that makes sense. We can always change this in the future if we want (the change would be very easy and not disruptive).

That seems sensible.

> IPos objects inherit a bunch of methods from IntegerRanges objects. Some of them (e.g.the comparison methods (==, <=, etc...), reduce(), coverage(), etc...) work as expected but could be overwritten by methods that are optimized for IPos objects. I'm putting this on the TODO list.

Yes, feature-complete(ish) but not necessarily optimised sounds like the best way to start.

Thanks!

**Comment by hpages** [comment]
So GPos got refactored to follow what happened to IPos: https://github.com/Bioconductor/GenomicRanges/commit/1ae56a95bf67a3e7acfc0d8365894fb2913b8124

Still need to work on the following:
- Have IPos and GPos objects support names.
- `updateObject()` methods to update old IPos/GPos instances.

Will skip the `pos()` setter for now.

H.

**Comment by hpages** [comment]
Hi Pete,

IPos and GPos objects can hold names in IRanges 2.19.9 and GenomicRanges 1.37.10.

Also added/updated `updateObject()` methods for IPos/GPos objects.

No `pos()` setter for these objects for now. Feel free to open an issue to request this if this is something you need.

H.

**Comment by PeteHaitch** [comment]
Hi Herve,
That's great!
Thank you very much.
I will start using the new *UnstitchedGPos* in **bsseq**

**Comment by hpages** [comment]
Good. FWIW today I improved the `IPos()` constructor so now it takes user-supplied names and metadata columns. This is in [IRanges 2.19.10](https://github.com/Bioconductor/IRanges/commit/f2cf3b5f31b499b2b5704562bd20586404f2dd47). Also finally added the long-overdue unit tests for IPos objects.

**Pull request closed without merging**
