### PR TITLE
tile() and slidingWindows() now preserve names

### PR DESCRIPTION
**Pull request by PeteHaitch**
This would've been useful to me the other day. Might help others, too

### CODE REVIEW

**Comment by hpages** [comment]
I'll let @lawremi take care of this one.

Heads-up: I'm not terribly happy with the current proliferation of "tiling tools" (`successiveIRanges()`, `successiveViews()`, `tileGenome()`, `tile()`, `slidingWindows()`, and maybe more...) with more or less overlap between them (see my comment at the top https://github.com/Bioconductor/IRanges/blob/master/R/tile-methods.R). This will need to be revisited at some point.

H.

**Comment by PeteHaitch** [comment]
I did see and appreciate those comments - I only learnt of `tile()` last
week! I'm hoping this change is small enough to include while the decision
about the various tools is worked through.

**Comment by mtmorgan** [comment]
@lawremi I'm not sure if you want to incorporate this patch or close the issue?

**Comment by lawremi** [comment]
Sorry I just missed this.

**Pull request merged**
